spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pos44ththqq
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      platform: postgres
